apiVersion: v1
kind: Service
metadata:
  name: bmi-app-service
spec:
  type: LoadBalancer  # MetalLB 사용 시 외부접속 가능
  selector:
    app: bmi-app
  ports:
  - protocol: TCP
    port: 80         # 클러스터 외부에서 접속할 포트
    targetPort: 3000 # 컨테이너 내에서 앱이 실행 중인 포트

